apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    io.kompose.service: chrome
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
      - image: ' '
        name: edx.devstack.chrome
        ports:
        - containerPort: 5900
        resources: {}
      hostname: chrome.devstack.edx
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.chrome
      from:
        kind: ImageStreamTag
        name: chrome:ironwood.master
    type: ImageChange
status: {}
