apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: devpi
  name: devpi
spec:
  replicas: 1
  selector:
    io.kompose.service: devpi
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: devpi
    spec:
      containers:
      - image: ' '
        name: edx-devstack-devpi
        ports:
        - containerPort: 3141
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: devpi-data
      hostname: devpi-devstack-edx
      restartPolicy: Always
      volumes:
      - name: devpi-data
        persistentVolumeClaim:
          claimName: devpi-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx-devstack-devpi
      from:
        kind: ImageStreamTag
        name: devpi:ironwood.master
    type: ImageChange
status: {}
