apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: devpi
  name: devpi
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: edxops/devpi:ironwood.master
    generation: null
    importPolicy: {}
    name: ironwood.master
status:
  dockerImageRepository: ""
