apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    io.kompose.service: discovery
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: discovery
    spec:
      containers:
      - args:
        - bash
        - -c
        - source /edx/app/discovery/discovery_env && while true; do python /edx/app/discovery/discovery/manage.py
          runserver 0.0.0.0:18381; sleep 2; done
        env:
        - name: ENABLE_DJANGO_TOOLBAR
          value: "1"
        - name: TEST_ELASTICSEARCH_URL
          value: http://edx.devstack.elasticsearch:9200
        image: ' '
        name: edx.devstack.discovery
        ports:
        - containerPort: 18381
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /edx/var/discovery/
          name: discovery-assets
        - mountPath: /edx/app/discovery/discovery/node_modules
          name: discovery-node-modules
      hostname: discovery.devstack.edx
      restartPolicy: Always
      volumes:
      - name: discovery-assets
        persistentVolumeClaim:
          claimName: discovery-assets
      - name: discovery-node-modules
        persistentVolumeClaim:
          claimName: discovery-node-modules
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.discovery
      from:
        kind: ImageStreamTag
        name: discovery:ironwood.master
    type: ImageChange
status: {}
