apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce
  name: ecommerce
spec:
  replicas: 1
  selector:
    io.kompose.service: ecommerce
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ecommerce
    spec:
      containers:
      - args:
        - bash
        - -c
        - source /edx/app/ecommerce/ecommerce_env && while true; do python /edx/app/ecommerce/ecommerce/manage.py
          runserver 0.0.0.0:18130; sleep 2; done
        env:
        - name: ENABLE_DJANGO_TOOLBAR
          value: "1"
        image: ' '
        name: edx.devstack.ecommerce
        ports:
        - containerPort: 18130
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /edx/app/ecommerce/ecommerce/node_modules
          name: ecommerce-node-modules
      hostname: ecommerce.devstack.edx
      restartPolicy: Always
      volumes:
      - name: ecommerce-node-modules
        persistentVolumeClaim:
          claimName: ecommerce-node-modules
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.ecommerce
      from:
        kind: ImageStreamTag
        name: ecommerce:ironwood.master
    type: ImageChange
status: {}
