apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: edx-notes-api
  name: edx-notes-api
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: edxops/notes:ironwood.master
    generation: null
    importPolicy: {}
    name: ironwood.master
status:
  dockerImageRepository: ""
