apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: edxops/elasticsearch:devstack
    generation: null
    importPolicy: {}
    name: devstack
status:
  dockerImageRepository: ""
