apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: forum
  name: forum
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: edxops/forum:ironwood.master
    generation: null
    importPolicy: {}
    name: ironwood.master
status:
  dockerImageRepository: ""
