apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: forum
  name: forum
spec:
  replicas: 1
  selector:
    io.kompose.service: forum
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: forum
    spec:
      containers:
      - args:
        - bash
        - -c
        - source /edx/app/forum/ruby_env && source /edx/app/forum/devstack_forum_env
          && cd /edx/app/forum/cs_comments_service && bundle install && while true;
          do ruby app.rb -o 0.0.0.0 ; sleep 2; done
        image: ' '
        name: edx.devstack.forum
        ports:
        - containerPort: 4567
        resources: {}
      hostname: forum.devstack.edx
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.forum
      from:
        kind: ImageStreamTag
        name: forum:ironwood.master
    type: ImageChange
status: {}
