apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gradebook
  name: gradebook
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: node:10
    generation: null
    importPolicy: {}
    name: "10"
status:
  dockerImageRepository: ""
