apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gradebook
  name: gradebook
spec:
  replicas: 1
  selector:
    io.kompose.service: gradebook
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gradebook
    spec:
      containers:
      - args:
        - bash
        - -c
        - npm install && npm run start
        env:
        - name: NODE_ENV
          value: development
        image: ' '
        name: edx.devstack.gradebook
        ports:
        - containerPort: 1994
        resources: {}
        volumeMounts:
        - mountPath: /edx/app/gradebook/node_modules
          name: gradebook-node-modules
        workingDir: /edx/app/gradebook
      restartPolicy: Always
      volumes:
      - name: gradebook-node-modules
        persistentVolumeClaim:
          claimName: gradebook-node-modules
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.gradebook
      from:
        kind: ImageStreamTag
        name: gradebook:10
    type: ImageChange
status: {}
