apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: lms
  name: lms
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gauravpatil/edxapp:ironwood.master
    generation: null
    importPolicy: {}
    name: ironwood.master
status:
  dockerImageRepository: ""
