apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    io.kompose.service: memcached
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: memcached
    spec:
      containers:
      - image: ' '
        name: edx.devstack.memcached
        resources: {}
      hostname: memcached.devstack.edx
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx.devstack.memcached
      from:
        kind: ImageStreamTag
        name: memcached:1.4.24
    type: ImageChange
status: {}
