apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: memcached:1.4.24
    generation: null
    importPolicy: {}
    name: 1.4.24
status:
  dockerImageRepository: ""
