apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    io.kompose.service: mongo
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        - --nojournal
        - --storageEngine
        - wiredTiger
        image: ' '
        name: edx-devstack-mongo
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      hostname: mongo-devstack-edx
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx-devstack-mongo
      from:
        kind: ImageStreamTag
        name: mongo:3.2.16
    type: ImageChange
status: {}
