apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kcompose --provider openshift convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    io.kompose.service: mysql
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        env:

        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          value: "root"
        image: ' '
        name: edx-devstack-mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      hostname: mysql-devstack-edx
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - edx-devstack-mysql
      from:
        kind: ImageStreamTag
        name: mysql:5.6
    type: ImageChange
status: {}
