apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv21
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 10.129.132.111 
    path: /var/nfs-data/pv21
  persistentVolumeReclaimPolicy: Recycle
    
