apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv26
spec:
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 10.129.132.111 
    path: /var/nfs-data/pv26
  persistentVolumeReclaimPolicy: Recycle
    
